[package]
name = "jvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#name = "jvm"
#path = "src/lib.rs"
#
#[[bin]]
#name = "jvm_main"
#path = "src/main.rs"

[dependencies]
byteorder = "1.4.3"
jvm_types = { path = "../jvm_types" }
parse_macro = { path = "../parse_macro" }
cesu8str = "0.2.4"
discrim = "0.1.1"
bitflags = "2.3.2"
parking_lot = "0.12.1"
cranelift-jit = "0.97.1"
cranelift = "0.97.1"
cranelift-module = "0.97.1"
cranelift-native = "0.97.1"
wasm-encoder = "0.29.0"
wasmprinter = "0.2.59"
wasmparser = "0.107.0"
wasmtime = "10.0.1"
indexmap = "2.0.0"
