[package]
name = "jvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jvm_types = { path = "../jvm_types" }
parse_macro = { path = "../parse_macro" }